# Generated by Django 3.2 on 2021-05-01 13:31

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default_profile.jpg', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
