# Generated by Django 3.2 on 2021-05-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boolean',
            field=models.BooleanField(),
        ),
    ]
